apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glmocr-backend-data
  namespace: glm-ocr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3